### ISSUE TITLE
Party tracking

### ISSUE THREAD

**Issue by keneanung** [AchaeaBashingScript/BashingPlugins#2]
With group bashing close to release, a party tracker add-on for the basher would be nice:
- [ ] A setup wizard to start the plugin
  - [ ] ask, whether party leader
  - [ ] recognise party members
  - [ ] allow modifiers for gold gain
  - [ ] ask user whether they want to change the battlerage strategy (and remember mode before!)
  - [ ] start a bashing trip
  - [ ] party invites
- [ ] Keep track of gold gathered (own, dedicated gatherer, collective gathering)
- [ ] Allow adding of new group members during the trip, starting at 0 gold (include modifiers)
- [ ] Allow removal of group members, show their gold
- [ ] Alarm when group member gets lost in leader mode
- [ ] Timer if target did not change for X minutes, ask whether the trip is finished
- [ ] when finished, restore battlerage strategy, show gold gains per participant

(This is a preleminary idea collection)
